services:
  # api:
  #   image: contract_payment_service
  #   container_name: contract_payment_service
  #   restart: always
  #   working_dir: /app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.docker
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #     - redis

  db:
    image: postgres:15.0-alpine
    container_name: contract_payment_service-db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env.docker
    ports:
      - name: db
        target: 5432
        host_ip: 127.0.0.1
        published: '5432'
        protocol: tcp
        app_protocol: http
        mode: host
    volumes:
      - db_data:/var/lib/postgresql/data/

  # redis:
  #   image: redis:7-alpine
  #   container_name: redis-server
  #   restart: always
  #   ports:
  #     - '6379:6379'

volumes:
  db_data:
    driver: local
