services:
  api:
    image: contract_payment_service_test
    container_name: contract_payment_service_test
    restart: always
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker.test
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    depends_on:
      - db_test
      - redis_test

  db_test:
    image: postgres:15.0-alpine
    container_name: contract_payment_service-db_test
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env.docker.test
    ports:
      - '5433:5432'
    volumes:
      - db_data_test:/var/lib/postgresql/data/
      # - ./postgres/init_test.sql:/docker-entrypoint-initdb.d/init.sql

  redis_test:
    image: redis:7-alpine
    container_name: redis-server_test
    restart: always
    ports:
      - '6380:6379'

volumes:
  db_data_test:
    driver: local
