name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.0-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        # Wait for the PostgreSQL service to be ready
        # before the next step in the job
        # timeout: 10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t contract_payment_system .

      - name: Run Docker container
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          docker run -d \
            --name contract_payment_system \
            --env POSTGRES_USER="$POSTGRES_USER" \
            --env POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            --env POSTGRES_DB="$POSTGRES_DB" \
            contract_payment_system

      - name: Run Tests
        run: |
          docker exec contract_payment_system \
            sh -c "npm run test" # Replace with your test command

      - name: Stop and Remove Docker container
        run: |
          docker stop contract_payment_system
          docker rm contract_payment_system
